dgr, thh, edd, hgn, Eiu = input().split()
dgr = int(dgr)
Eiu = int(Eiu)
hgn = int(hgn)
edd = int(edd)
thh = int(thh)
a = (dgr * dgr)
b = (Eiu * Eiu)
c = (hgn * hgn)
d = (edd * edd)
e = (thh * thh)

dks = (a + b + c + d + e)
print(dks % 10)
